
/*Design the "Students" table to store student details*/
CREATE TABLE STUDENTS(
STUDENTID INT PRIMARY KEY,
FIRSTNAME VARCHAR (50),
LASTNAME VARCHAR(50),
AGE INT,
MAJOR VARCHAR (50)
);

/*inserting data in the students table */
INSERT INTO STUDENTS(STUDENTID,FIRSTNAME,LASTNAME,AGE,MAJOR)
VALUES
(1,'KEAM','KEYMONEY',25,'COMPUTER SCIENCE'),
(2,'IAN','HERBALIST',24, 'FOOD SCIENCE'),
(3,'BONNIE','KIM',27,'FINANCE'),
(4,'ASSU','NGINAH',28,'AGRONOMY'),
(5,'JLO','MSOH',26,'MATHEMATICS');

ALTER TABLE STUDENTS
/*ADDING A NEW COLUMN TO AN EXISTING TABLE */
add column GPA DECIMAL(4,3);

/*Add a new column "GPA" to the "Students" table to store students' Grade Point Average*/
UPDATE Students
SET GPA = 5
WHERE StudentID <= 5;

ALTER TABLE STUDENTS
/*WE USE ALTER TABLE NAME FOLLOWED BY RENAME KEYWORD TO DESIRED TABLE NAME */
RENAME TO ENROLLEDSTUDENTS

/*designing courses table to store courses details related to students */
CREATE TABLE COURSES(
COURSEID INT PRIMARY KEY,
COURSENAME VARCHAR (100),
INSTRUCTOR VARCHAR (100),
CREDITS int
);

/*inserting data into the course table*/
INSERT INTO COURSES
VALUES
(1,'MATHEMATICS','EDDY PLP',3),
(2,'FINANCE','STEVE MUNGA',2),
(3,'COMPUTER SCIENCE','SUSAN',1),
(4,'AGROMONY','ZABLON',5);


DROP TABLE enrolledstudents;
/*DROP IS USED TO DELETE AN EXISTING TABLE IN A DATABASE */







